CATEGORY_GROUP_MAP = {

    # ───────── HUMAN / CULTURE ─────────
    "1001 nights": "Middle Eastern / Arabian",
    "arabic": "Middle Eastern / Arabian",
    "berber /amazigh": "Middle Eastern / Arabian",
    "assyrian": "Middle Eastern / Arabian",
    "egyptian": "Middle Eastern / Arabian",
    "fantasy egyptian": "Middle Eastern / Arabian",
    "zakharans": "Middle Eastern / Arabian",
    "calishites": "Middle Eastern / Arabian",
    "middleeastern": "Middle Eastern / Arabian",

    "north indian hindu": "South Asian",
    "pahari": "South Asian",

    "american names": "Human (Modern)",
    "brazilian": "Human (Modern)",
    "british female": "Human (Modern)",
    "british male": "Human (Modern)",
    "british surnames": "Human (Modern)",
    "englishy": "Human (Modern)",
    "czech": "Human (Modern)",
    "danish": "Human (Modern)",
    "hungarian": "Human (Modern)",
    "irish": "Human (Modern)",
    "italian": "Human (Modern)",
    "italiano": "Human (Modern)",
    "jamaican": "Human (Modern)",
    "mongolian": "Human (Modern)",
    "nordic": "Human (Modern)",
    "spanish": "Human (Modern)",
    "united kingdom": "Human (Modern)",

    "chinese given names": "East Asian",
    "hk/cantonese fem. given names": "East Asian",
    "hk/cantonese male given names": "East Asian",
    "japanese": "East Asian",
    "korean": "East Asian",
    "shou": "East Asian",
    "tengu": "East Asian",
    "korobokuru": "East Asian",

    "aztec /nahuatl": "Mesoamerican",
    "mayan": "Mesoamerican",
    "mazticans": "Mesoamerican",

    "ancient surnames": "Human (General)",
    "common surnames": "Human (General)",
    "last names": "Human (General)",
    "surnames": "Human (General)",
    "surnames one": "Human (General)",

    "male": "Human (General)",
    "female": "Human (General)",
    "realistic male": "Human (General)",
    "realistic female": "Human (General)",
    "male names": "Human (General)",
    "female names": "Human (General)",

    # ───────── ELVES & FEY ─────────
    "elves": "Elves",
    "high elves": "Elves",
    "moon elves": "Elves",
    "sun elves": "Elves",
    "wood elves": "Elves",
    "wild elves": "Elves",
    "star elves": "Elves",
    "aquatic elves": "Elves",
    "dark elves": "Elves",
    "drow": "Elves",
    "half-elves": "Elves",
    "avariel": "Elves",
    "llewyrr": "Elves",
    "lythari": "Elves",

    "eladrin": "Fey",
    "celadrin": "Fey",
    "noble eladrin": "Fey",
    "archfey": "Fey",
    "fae public names": "Fey",
    "nymphs": "Fey",
    "dryads": "Fey",
    "satyrs": "Fey",
    "korreds": "Fey",
    "hybsils": "Fey",
    "quicklings": "Fey",
    "sprites": "Fey",
    "pixies": "Fey",
    "voadkyn": "Fey",
    "verdant princes": "Fey",
    "wood woads": "Fey",

    # ───────── DWARVES / GNOMES / HALFLINGS ─────────
    "dwarves": "Dwarves",
    "gold dwarves": "Dwarves",
    "shield dwarves": "Dwarves",
    "chultan dwarves": "Dwarves",

    "gnomes": "Gnomes",
    "deep gnomes": "Gnomes",
    "forest gnomes": "Gnomes",
    "rock gnomes": "Gnomes",

    "halflings": "Halflings",
    "lightfoot halflings": "Halflings",
    "ghostwise halflings": "Halflings",
    "strongheart halflings": "Halflings",

    # ───────── CELESTIALS ─────────
    "celestials": "Celestials",
    "celestials (5e)": "Celestials",
    "angels": "Celestials",
    "fallen angels": "Celestials",
    "planetars": "Celestials",
    "solars": "Celestials",
    "devas": "Celestials",
    "astral devas": "Celestials",
    "aasimar": "Celestials",
    "devas (aasimar)": "Celestials",
    "half-celestials": "Celestials",
    "tome archons": "Celestials",
    "trumpet archons": "Celestials",
    "ursinals": "Celestials",
    "leonals": "Celestials",
    "hollyphants": "Celestials",

    # ───────── FIENDS ─────────
    "demons": "Fiends",
    "demon lords": "Fiends",
    "devils": "Fiends",
    "archdevils": "Fiends",
    "pit fiends": "Fiends",
    "succubi": "Fiends",
    "incubi": "Fiends",
    "cambions": "Fiends",
    "half-fiends": "Fiends",
    "alu-fiends": "Fiends",
    "yugoloths": "Fiends",
    "tanar'ri": "Fiends",
    "obyriths": "Fiends",

    # ───────── DRAGONS ─────────
    "dragons": "Dragons",
    "dragonborn": "Dragons",
    "half-dragons": "Dragons",
    "dracoliches": "Dragons",
    "dragon turtles": "Dragons",
    "pseudodragons": "Dragons",
    "wyverns": "Dragons",

    # ───────── UNDEAD ─────────
    "liches": "Undead",
    "demiliches": "Undead",
    "baelnorn liches": "Undead",
    "ghosts": "Undead",
    "ghouls": "Undead",
    "ghasts": "Undead",
    "wraiths": "Undead",
    "specters": "Undead",
    "revenants": "Undead",
    "vampires": "Undead",
    "vampire spawn": "Undead",
    "skeletons": "Undead",
    "zombies": "Undead",
    "mummies": "Undead",
    "mummy lords": "Undead",

    # ───────── ABERRATIONS ─────────
    "mind flayers": "Aberrations",
    "elder brains": "Aberrations",
    "beholders": "Aberrations",
    "gibbering mouthers": "Aberrations",
    "aboleths": "Aberrations",
    "intellect devourers": "Aberrations",
    "deepspawns": "Aberrations",
    "osquips": "Aberrations",

    # ───────── BEASTS ─────────
    "bears": "Beasts",
    "brown bears": "Beasts",
    "wolves": "Beasts",
    "dire wolves": "Beasts",
    "winter wolves": "Beasts",
    "cats": "Beasts",
    "dogs": "Beasts",
    "rats": "Beasts",
    "horses": "Beasts",
    "whales": "Beasts",
    "hamsters": "Beasts",
    "giant space hamsters": "Beasts",
    "owls": "Beasts",
    "hawks": "Beasts",
    "eagles": "Beasts",
    "falcons": "Beasts",

    # ───────── CONSTRUCTS ─────────
    "constructs": "Constructs",
    "golems": "Constructs",
    "animated armors": "Constructs",
    "helmed horrors": "Constructs",
    "nimblewrights": "Constructs",
    "living spells": "Constructs",
    "warforged": "Constructs",
    "walking statues of waterdeep": "Constructs",

    # Rest
    "aarakocra": "Beastfolk",
    "abbalayar": "Monstrosities",
    "abominations": "Monstrosities",
    "administrator genies": "Genies",
    "air elementals": "Elementals",
    "alaghi": "Monstrosities",
    "alhoons": "Undead",
    "allips": "Undead",
    "almiraj": "Beasts",
    "altraloths": "Yugoloths",
    "amazons": "Human (General)",
    "amethyst dragons": "Dragons",
    "amiq rasol": "Human (General)",
    "amnizus": "Fiends",
    "androsphinxes": "Monstrosities",
    "angels and demons": "Outsiders",
    "angels of decay": "Celestials",
    "animal lords": "Celestials",
    "ankylosauruses": "Beasts",
    "annises": "Fey",
    "arcanaloths": "Yugoloths",
    "arcane": "Organizations / Meta",
    "archfiends": "Fiends",
    "archliches": "Undead",
    "archomentals": "Elementals",
    "artist genies": "Genies",
    "asabis": "Beastfolk",
    "asianish": "East Asian",
    "aspects": "Spirits",
    "aspects of chauntea": "Celestials",
    "asuras": "Fiends",
    "atropals": "Undead",
    "avolakia": "Undead",
    "avorals": "Celestials",
    "azers": "Elementals",
    "baatezu": "Fiends",
    "badgers": "Beasts",
    "bakemono": "Goblinoids",
    "baker street": "Human (Modern)",
    "balors": "Fiends",
    "baltic": "Human (Modern)",
    "bamboo spirit folk": "Spirits",
    "banelar nagas": "Monstrosities",
    "banshees": "Undead",
    "barbazus": "Fiends",
    "barghests": "Fiends",
    "basilisks": "Monstrosities",
    "bats": "Beasts",
    "behirs": "Monstrosities",
    "bheurs": "Fey",
    "black clouds of vengeance": "Spirits",
    "black dragons": "Dragons",
    "black firedrakes": "Dragons",
    "blade golems": "Constructs",
    "blight wyrms": "Dragons",
    "blood fiends": "Fiends",
    "blue dragons": "Dragons",
    "blue slaadi": "Aberrations",
    "boars": "Beasts",
    "bone devils": "Fiends",
    "bone nagas": "Undead",
    "brains in jars": "Undead",
    "bralani": "Celestials",
    "brass dragons": "Dragons",
    "bronze dragons": "Dragons",
    "brown dragons": "Dragons",
    "brownies": "Fey",
    "bugbears": "Goblinoids",
    "bullywugs": "Beastfolk",
    "butu": "Monstrosities",
    "camels": "Beasts",
    "celestial eladrin": "Celestials",
    "celestial paragons": "Celestials",
    "centaurs": "Beastfolk",
    "chiang lung": "Dragons",
    "chimeras": "Monstrosities",
    "chondathans": "Human (General)",
    "chultans": "Human (General)",
    "clay golems": "Constructs",
    "cloud giant clans": "Giants",
    "cloud giants": "Giants",
    "coombe giants": "Giants",
    "copper dragons": "Dragons",
    "cornugons": "Fiends",
    "corpse tearer linnorms": "Dragons",
    "couatls": "Celestials",
    "crinti": "Elves",
    "crocodiles": "Beasts",
    "crystal dragons": "Dragons",
    "cursts": "Undead",
    "d'tarig": "Monstrosities",
    "damarans": "Human (General)",
    "dao": "Genies",
    "daolani": "Genies",
    "dark nagas": "Monstrosities",
    "death knights": "Undead",
    "death slaadi": "Aberrations",
    "deep bats": "Beasts",
    "deep dragons": "Dragons",
    "deinonychuses": "Beasts",
    "derro": "Dwarves",
    "desert centaurs": "Beastfolk",
    "dire badgers": "Beasts",
    "dire boars": "Beasts",
    "displacer beasts": "Monstrosities",
    "djinn": "Genies",
    "djinnlings": "Genies",
    "donkeys": "Beasts",
    "doppelgangers": "Monstrosities",
    "draegloths": "Fiends",
    "dragonborn of bahamut": "Dragons",
    "dread wraiths": "Undead",
    "driders": "Monstrosities",
    "drow-dragons": "Dragons",
    "duergar": "Dwarves",
    "duruch'i-lin": "Monstrosities",
    "durzagon": "Dwarves",
    "earth elementals": "Elementals",
    "earth genasi": "Genies",
    "eblis": "Beastfolk",
    "efreet": "Genies",
    "efreetikin": "Genies",
    "elephants": "Beasts",
    "emerald dragons": "Dragons",
    "erinyes": "Fiends",
    "ettins": "Giants",
    "faerie dragons": "Dragons",
    "fang dragons": "Dragons",
    "fell trolls": "Monstrosities",
    "female names one": "Human (General)",
    "female names three": "Human (General)",
    "fey'ri": "Planar Hybrids",
    "fiendish creatures": "Fiends",
    "fiends": "Fiends",
    "filipino": "Human (Modern)",
    "firbolg clans": "Giants",
    "firbolgs": "Giants",
    "fire elemental myrmidons": "Elementals",
    "fire elementals": "Elementals",
    "fire genasi": "Genies",
    "fire giants": "Giants",
    "fire mephits": "Elementals",
    "firenewts": "Beastfolk",
    "flail snails": "Monstrosities",
    "flameskulls": "Undead",
    "flesh golems": "Constructs",
    "flinds": "Gnolls",
    "flumphs": "Aberrations",
    "fomorians": "Giants",
    "froghemoths": "Monstrosities",
    "frost giants": "Giants",
    "galeb duhrs": "Elementals",
    "gargantuan spiders": "Beasts",
    "gargoyles": "Elementals",
    "gelatinous cubes": "Oozes",
    "gelugons": "Fiends",
    "genasi": "Genies",
    "generalwest": "Organizations / Meta",
    "generalwest2": "Organizations / Meta",
    "genies": "Genies",
    "ghazneths": "Undead",
    "ghul-kin": "Undead",
    "giant fire beetles": "Beasts",
    "giant spiders": "Beasts",
    "giff": "Beastfolk",
    "gith": "Gith",
    "githvyrik": "Gith",
    "githyanki": "Gith",
    "githzerai": "Gith",
    "glabrezus": "Fiends",
    "gloamings": "Spirits",
    "gnolls": "Gnolls",
    "goblin tribes": "Goblinoids",
    "goblins": "Goblinoids",
    "gold dragons": "Dragons",
    "goliaths": "Giants",
    "gondsmen": "Human (General)",
    "gorgons": "Monstrosities",
    "gray oozes": "Oozes",
    "gray orcs": "Orcs",
    "great ghuls": "Undead",
    "greece": "Human (Modern)",
    "greek (modern)": "Human (Modern)",
    "green dragons": "Dragons",
    "green hags": "Fey",
    "griffons": "Monstrosities",
    "grimlocks": "Monstrosities",
    "grippli": "Beastfolk",
    "grisgols": "Constructs",
    "grungs": "Beastfolk",
    "guardian genies": "Genies",
    "guardian nagas": "Monstrosities",
    "gulguthras": "Aberrations",
    "gynosphinxes": "Monstrosities",
    "hadozee": "Beastfolk",
    "hagspawn": "Fey",
    "half-demons": "Planar Hybrids",
    "half-devils": "Planar Hybrids",
    "half-drow": "Elves",
    "half-dwarves": "Dwarves",
    "half-golems": "Constructs",
    "half-humans": "Human (General)",
    "half-ogres": "Giants",
    "half-oni": "Planar Hybrids",
    "half-orcs": "Orcs",
    "halruaans": "Human (General)",
    "hamatulas": "Fiends",
    "haraknins": "Monstrosities",
    "harengons": "Beastfolk",
    "harim servant genies": "Genies",
    "hell hounds": "Fiends",
    "hengeyokai": "Beastfolk",
    "hezrou": "Fiends",
    "hill giants": "Giants",
    "hippopotami": "Beasts",
    "hobgoblins": "Goblinoids",
    "homunculi": "Constructs",
    "hook horrors": "Monstrosities",
    "huge spiders": "Beasts",
    "humans": "Human (General)",
    "hunting spider katanga": "Beasts",
    "ice mephits": "Elementals",
    "ice para-elementals": "Elementals",
    "ice spire ogres": "Giants",
    "ice toads": "Beasts",
    "illuskans": "Human (General)",
    "imps": "Fiends",
    "invisible stalkers": "Elementals",
    "ixitxachitls": "Aberrations",
    "ixzan": "Monstrosities",
    "jackalweres": "Beastfolk",
    "jaculis": "Monstrosities",
    "jagres": "Monstrosities",
    "jann": "Genies",
    "kamadans": "Monstrosities",
    "katanga": "Human (Modern)",
    "keening spirits": "Spirits",
    "kender": "Halflings",
    "kenku": "Beastfolk",
    "kir-lanan": "Beastfolk",
    "kobolds": "Kobolds",
    "krakens": "Monstrosities",
    "kuo-toa": "Monstrosities",
    "kytons": "Fiends",
    "lakshu": "Monstrosities",
    "lamia nobles": "Monstrosities",
    "lamias": "Monstrosities",
    "lava children": "Elementals",
    "leshay": "Fey",
    "leviathans": "Monstrosities",
    "lizardfolk": "Beastfolk",
    "locathah": "Beastfolk",
    "longdragon_or_minotaur": "Dragons",
    "loxos": "Beastfolk",
    "lupinals": "Celestials",
    "maedar": "Monstrosities",
    "malaugrym": "Monstrosities",
    "male names 1": "Human (General)",
    "male names 2": "Human (General)",
    "male names 4": "Human (General)",
    "male names three": "Human (General)",
    "malenti": "Beastfolk",
    "maridans": "Genies",
    "marids": "Genies",
    "mariella)": "Human (General)",
    "mariliths": "Fiends",
    "markeen": "Human (General)",
    "marrash": "Monstrosities",
    "maztican dragons": "Dragons",
    "me-zu oni": "Fiends",
    "meazels": "Monstrosities",
    "medusae": "Monstrosities",
    "mephits": "Elementals",
    "mercury dragons": "Dragons",
    "merfolk": "Beastfolk",
    "merrow (ogres)": "Giants",
    "mezzoloths": "Yugoloths",
    "mimics": "Monstrosities",
    "miniature giant space hamsters": "Beasts",
    "minotaurs": "Beastfolk",
    "mist dragons": "Dragons",
    "modrons": "Constructs",
    "molydei": "Fiends",
    "moorhounds": "Monstrosities",
    "morkoths": "Aberrations",
    "mountain giants": "Giants",
    "mountain orcs": "Orcs",
    "mountain spirit folk": "Spirits",
    "mulani": "Human (General)",
    "mules": "Beasts",
    "myconids": "Plants",
    "nabassus": "Fiends",
    "nalfeshnee": "Fiends",
    "nars": "Monstrosities",
    "nats": "Spirits",
    "nereids": "Fey",
    "netherese": "Human (General)",
    "nico)": "Human (General)",
    "night hags": "Fey",
    "nighthaunts": "Undead",
    "nightmares": "Fiends",
    "nishruu": "Aberrations",
    "noble marids": "Genies",
    "northlanders": "Human (General)",
    "novieres": "Celestials",
    "nycaloths": "Yugoloths",
    "oathbinder genies": "Genies",
    "ogre giants": "Giants",
    "ogres": "Giants",
    "ogrillons": "Giants",
    "oinoloths": "Yugoloths",
    "olsen": "Human (General)",
    "oni": "Fiends",
    "oni magi": "Fiends",
    "oni night haunters": "Fiends",
    "ophidians": "Beastfolk",
    "orc clans and tribes": "Orcs",
    "orcs": "Orcs",
    "organizations in the cavern of cloven heads": "Organizations / Meta",
    "organizations in the darklands": "Organizations / Meta",
    "organizations in the underdark": "Organizations / Meta",
    "ormyrr": "Monstrosities",
    "orogs": "Orcs",
    "oscray": "Human (General)",
    "osyluths": "Fiends",
    "otyughs": "Monstrosities",
    "outsiders": "Outsiders",
    "outsiders (3e)": "Outsiders",
    "owlbears": "Monstrosities",
    "pan lung": "Dragons",
    "pechs": "Fey",
    "pegasi": "Celestials",
    "personal /social list": "Organizations / Meta",
    "phaerimm": "Aberrations",
    "phoenixes": "Celestials",
    "pigs": "Beasts",
    "planetouched": "Planar Hybrids",
    "platinum dragons": "Dragons",
    "ponies": "Beasts",
    "primal spirits": "Spirits",
    "princes of shade": "Human (General)",
    "pterafolk": "Beastfolk",
    "quaggoths": "Monstrosities",
    "quasits": "Fiends",
    "rakshasas": "Fiends",
    "raptorans": "Beastfolk",
    "rashemi": "Human (General)",
    "raumvirans": "Human (General)",
    "ravens": "Beasts",
    "red dragons": "Dragons",
    "redcaps": "Fey",
    "reef giants": "Giants",
    "reghedmen": "Human (General)",
    "renzo)": "Human (General)",
    "rilmani": "Outsiders",
    "river spirit folk": "Spirits",
    "rocs": "Beasts",
    "ropers": "Monstrosities",
    "rosella": "Human (General)",
    "ruby dragons": "Dragons",
    "sahuagin": "Beastfolk",
    "salamanders": "Elementals",
    "sapphire dragons": "Dragons",
    "sarrukh": "Beastfolk",
    "saru": "Beastfolk",
    "saurials": "Beastfolk",
    "scaladars": "Monstrosities",
    "scrags": "Monstrosities",
    "scro": "Orcs",
    "sea drakes": "Dragons",
    "sea hags": "Fey",
    "sea spirit folk": "Spirits",
    "sea wyrms": "Dragons",
    "shadar-kai": "Fey",
    "shades": "Undead",
    "shadovar": "Human (General)",
    "shadow demons": "Fiends",
    "shadow dragons": "Dragons",
    "shadows": "Undead",
    "shadowstaves": "Undead",
    "shadurakul": "Human (General)",
    "shalarin": "Beastfolk",
    "shen lung": "Dragons",
    "shifters": "Beastfolk",
    "silver dragons": "Dragons",
    "simurghs": "Celestials",
    "sirines": "Fey",
    "skulks": "Monstrosities",
    "slaad lords": "Aberrations",
    "slaadi": "Aberrations",
    "slayer genies": "Genies",
    "slimes": "Oozes",
    "smoke drakes": "Dragons",
    "song dragons": "Dragons",
    "spectators": "Aberrations",
    "spider katanga": "Beasts",
    "spirit folk": "Spirits",
    "spirit nagas": "Monstrosities",
    "spirits": "Spirits",
    "squirrels": "Beasts",
    "steel dragons": "Dragons",
    "stone giants": "Giants",
    "stone golems": "Constructs",
    "storm elementals": "Elementals",
    "storm giants": "Giants",
    "story games names project": "Organizations / Meta",
    "sunwyrms": "Dragons",
    "swanmays": "Beastfolk",
    "t'ien lung": "Dragons",
    "tabaxi": "Beastfolk",
    "taers": "Giants",
    "tainted ones": "Fiends",
    "talking birds": "Beasts",
    "tanarukk": "Planar Hybrids",
    "tasked genies": "Genies",
    "tasloi": "Monstrosities",
    "tattooed land": "Human (General)",
    "tethyrians": "Human (General)",
    "thorns": "Plants",
    "thri-kreen": "Beastfolk",
    "tieflings": "Planar Hybrids",
    "tigers": "Beasts",
    "titans": "Giants",
    "topaz dragons": "Dragons",
    "tortles": "Beastfolk",
    "treants": "Plants",
    "tressym": "Beasts",
    "tricksters": "Spirits",
    "tritons": "Beastfolk",
    "troglodytes": "Beastfolk",
    "trolls": "Monstrosities",
    "tulani": "Celestials",
    "two- fisted space opera": "Organizations / Meta",
    "tyrannosaurs": "Beasts",
    "ultroloths": "Yugoloths",
    "unicorns": "Celestials",
    "uridezu": "Fiends",
    "vaasans": "Human (General)",
    "vegepygmies": "Plants",
    "venerian": "Human (Modern)",
    "verbeegs": "Giants",
    "vishap": "Dragons",
    "vizier's turbans": "Organizations / Meta",
    "volodni": "Plants",
    "vrocks": "Fiends",
    "war devils": "Fiends",
    "warmonger genies": "Genies",
    "water elementals": "Elementals",
    "water genasi": "Genies",
    "water nagas": "Monstrosities",
    "watersoul genasi": "Genies",
    "weasels": "Beasts",
    "weirdgoblin": "Goblinoids",
    "wemics": "Beastfolk",
    "werebats": "Beastfolk",
    "werebears": "Beastfolk",
    "wereboars": "Beastfolk",
    "werecats": "Beastfolk",
    "weredragons": "Beastfolk",
    "werefoxes": "Beastfolk",
    "werelions": "Beastfolk",
    "wererats": "Beastfolk",
    "weretigers": "Beastfolk",
    "werewolves": "Beastfolk",
    "werewyverns": "Beastfolk",
    "white abishai": "Fiends",
    "white dragons": "Dragons",
    "wights": "Undead",
    "winemaker genies": "Genies",
    "winged cats": "Beasts",
    "winged kenku": "Beastfolk",
    "wolfweres": "Beastfolk",
    "worgs": "Monstrosities",
    "worshipers of the faceless god": "Organizations / Meta",
    "xvarts": "Goblinoids",
    "yak folk": "Beastfolk",
    "yochlols": "Fiends",
    "you all meet in a tavern": "Organizations / Meta",
    "yuan-ti": "Yuan-ti",
    "yuan-ti abominations": "Yuan-ti",
    "yuan-ti anathemas": "Yuan-ti",
    "yuan-ti malisons": "Yuan-ti",
    "yuan-ti purebloods": "Yuan-ti",
    "zin-carla": "Undead",
}

